version: "3.9"
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: challenge_db
      MYSQL_USER: armando
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - my_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "443:443"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: challenge_db
      DB_USER: armando
      DB_PASSWORD: 123456
    depends_on:
      - db
    command: >
      /bin/sh -c "dotnet ef database update &&
                  dotnet challenge.dll"
    networks:
      - my_network

volumes:
  db_data:

networks:
  my_network:
