// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using challenge.Database;

#nullable disable

namespace challenge.Migrations
{
    [DbContext(typeof(BancoContext))]
    [Migration("20230430175031_AjusteConta2")]
    partial class AjusteConta2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("challenge.Models.ContaBancaria", b =>
                {
                    b.Property<int?>("Conta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Saldo")
                        .HasColumnType("double");

                    b.HasKey("Conta");

                    b.ToTable("ContasBancaria");
                });
#pragma warning restore 612, 618
        }
    }
}
